# Generated by Django 5.2.1 on 2025-05-21 18:09

import django.core.validators
import django.db.models.deletion
import model.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(validators=[model.models.validate_timestamp_order])),
                ('severity', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], max_length=10)),
                ('message', models.TextField()),
                ('source', models.CharField(max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='model_logen_timesta_736277_idx'), models.Index(fields=['severity'], name='model_logen_severit_83605e_idx')],
            },
        ),
        migrations.CreateModel(
            name='AnomalyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anomaly_score', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('detection_timestamp', models.DateTimeField(auto_now_add=True)),
                ('model_version', models.CharField(max_length=50)),
                ('summary', models.TextField()),
                ('is_acknowledged', models.BooleanField(default=False)),
                ('log_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomalies', to='model.logentry')),
            ],
            options={
                'ordering': ['-detection_timestamp'],
                'indexes': [models.Index(fields=['anomaly_score'], name='model_anoma_anomaly_0f3b6c_idx'), models.Index(fields=['detection_timestamp'], name='model_anoma_detecti_4b6a69_idx')],
            },
        ),
    ]
